title: Benchmark Results
description: A collection of model benchmark results
baseurl: "/benchmarks"
url: "https://olyasir.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  results:
    output: true
    permalink: /results/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "results"
    values:
      layout: "result" 