title: Benchmark Results
description: A collection of model benchmark results
baseurl: "/benchmarks"
url: "https://olyasir.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  results:
    output: true
    permalink: /results/:name/
    sort_by: date
    sort_order: reverse

# Defaults
defaults:
  - scope:
      path: "results"
      type: "results"
    values:
      layout: "result"
      category: "benchmarks"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github 